---
- name : Install & run Containerd
  hosts: all
  become: yes
  gather_facts: no

  tasks:

  - name: Install dependency
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - ntp
      state: latest
      update_cache: yes

  - name: Add gpg-key of Docker repo
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
      state: present


  - name: Update apt and install containerd
    apt:
      update_cache: yes
      name: containerd
      state: latest

  - name: Make containerd catalog
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
      owner: root
      group: root
    loop:
      - "/etc/containerd"

  - name: Copy containerd/config file
    copy:
      src: ./configs/containerd/config.toml
      dest: /etc/containerd/
      mode: 0755
      owner: root
      group: root

  - name: Start containerd and enabled
    service: name=containerd state=started enabled=yes

  - name: Start ntpd and enabled
    service: name=ntp state=started enabled=yes
