---
- name : Install & run Containerd
  hosts: all
  become: yes
  gather_facts: no

  tasks:

  - name: Download crictl
    unarchive:
      src: 'https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.23.0/crictl-v1.23.0-linux-amd64.tar.gz'
      dest: /usr/bin
      remote_src: yes

  - name: Download nerdctl
    unarchive:
      src: 'https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-amd64.tar.gz'
      dest: /usr/bin
      remote_src: yes

  - name: Copy crictl config file
    copy:
      src: ./configs/crictl/crictl.yaml
      dest: /etc/
      mode: 0755
      owner: root
      group: root

  - name: Copy k8s.conf
    copy:
      src: ./configs/kube/k8s.conf
      dest: /etc/sysctl.d/
      mode: 0755
      owner: root
      group: root


  - name: Enable k8s.conf
    shell: 'sysctl --system'
