---
- block:

    - name: Generate dashboard ingress rule file
      template:
        src: prometheus-stack-ingress.j2
        dest: $HOME/prometheus-stack-ingress.yml

    - name: Apply dashboard ingress rule
      shell: kubectl apply -f prometheus-stack-ingress.yml
      args:
        chdir: $HOME

  when: "'k8s-master01' in ansible_hostname"