---
- block:


    - name: Generate coredns.sh script
      template:
        src: coredns.j2
        dest: $HOME/coredns.sh
        mode: 0700

    - name: Run script to assign coredns in controlplane
      shell: "./coredns.sh"
      args:
        chdir: $HOME

  when: ansible_facts['hostname'] == "k8s-master01"