---
- block:

    - name: Generate Nginx-ingress manifest file
      template:
        src: nginx-ingress.j2
        dest: $HOME/nginx-ingress.yml

    - name: Install Nginx helm chart
      helm:
        host: localhost
        chart:
          name: ingress-nginx/ingress-nginx
          source:
            type: repo
            location: https://kubernetes.github.io/ingress-nginx
        state: present
        name: ingress-nginx
        namespace: nginx-ingress
        values: "{{ lookup('template', 'nginx-ingress.yml') | from_yaml }}"
      args:
        chdir: $HOME

#    - name: Edit Nginx-ingress-class from manifest file
#      shell: kubectl apply -f nginx-ingress.yml
#      args:
#        chdir: $HOME

  when: "'k8s-master01' in ansible_hostname"