---
- block:

    - name: Generate NodeLocal DNSCache manifest file
      template:
        src: nodelocaldns.j2
        dest: $HOME/nodelocaldns.yml

    - name: Install NodeLocal DNSCache from manifest file
      shell: kubectl apply -f nodelocaldns.yml
      args:
        chdir: $HOME

  when: "'k8s-master01' in ansible_hostname"