---
- block:

    - name: Add prometheus-community chart repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Install kube-prometheus-stack helm chart
      kubernetes.core.helm:
        chart_ref: prometheus-community/kube-prometheus-stack
        release_name: kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        update_repo_cache: True
        values:
          grafana:
            ingress:
              enabled: true
            hosts:
              - grafana.musin.tech
            paths:
              - /
          prometheus:
            ingress:
              enabled: true
              hosts:
                - prometheus.musin.tech
              paths:
                - /
            prometheusSpec:
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: local-storage
                    accessModes: [ "ReadWriteOnce" ]
                    resources:
                      requests:
                        storage: 10Gi

  when: ansible_facts['hostname'] == "k8s-master01"