---
- name: Add the OS variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Change NodeSelector in CoreDNS deployment
  include_tasks: change_coredns_nodeselector.yml

- name: Install NodeLocal DNSCache
  include_tasks: install_nodelocal.yml

- name: Install Nginx ingress-controller
  include_tasks: install-nginx-ingress.yml

- name: Install Kubernetes Dashboard
  include_tasks: install-dashboard.yml

- name: Install metrics-server
  include_tasks: install-metrics-server.yml

- name: Add ingress rules for Dashboard
  include_tasks: add_dashboard_ingress.yml

#- name: Install nfs-provisioner
#  include_tasks: install-nfs-provisioner.yml
#
#- name: Install Kube-prometheus-stack
#  include_tasks: install-prometheus-stack.yml

#- name: Add ingress rules for Kube-prometheus-stack
#  include_tasks: add_prometheus_grafana_ingresses.yml

#- name: Install jenkins
#  include_tasks: install_jenkins.yml

#
