---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs-client-provisioner
parameters:
  archiveOnDelete: "false"
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer