---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: nexus
spec:
  ingressClassName: nginx
  rules:
    - host: nexus.cluster.local
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nexus-repository-manager
                port:
                  number: 8081
            path: /

    - host: docker.cluster.local
      http:
        paths:
            - pathType: Prefix
              backend:
                service:
                  name: nexus-repository-manager
                  port:
                    number: 8082
              path: /

#  tls:
#    - secretName: nexus-tls
#      hosts:
#      - docker.cluster.local