---
- block:

    - name: Generate kube-prometheus-stack ingress rules file
      template:
        src: prometheus-stack-ingress.j2
        dest: $HOME/prometheus-stack-ingress.yml

    - name: Apply kube-prometheus-stack ingress rules
      shell: kubectl apply -f prometheus-stack-ingress.yml
      args:
        chdir: $HOME

  when: "'k8s-master01' in ansible_hostname"