---
- block:

    - name: Generate labels.sh script
      template:
        src: hosts.j2
        dest: $HOME/labels.sh
        mode: 0700

    - name: Add labels on nodes & taints on ingresses
#      shell: $HOME/labels.sh
      shell: "kubectl taint nodes $(hostname) node-role.kubernetes.io/master:NoSchedule-"
#      args:
#        chdir: $HOME

  when: "'k8s-master01' in ansible_hostname"