---
- block:

    - name: Load required modules
      modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - br_netfilter
        - overlay

    - name: Copy kube-init.yaml with Harbor
      template:
        src: kube-init-harbor.j2
        dest: $HOME/kube-init.yml
      when: harbor_use == true

    - name: Copy kube-init.yaml
      template:
        src: kube-init.j2
        dest: $HOME/kube-init.yml
      when: harbor_use == false

    - name: Initialize the cluster
      shell: kubeadm init --config kube-init.yml --upload-certs | tee -a kube_init.log
      args:
        chdir: $HOME

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: root
        mode: 0600

  when: ansible_facts['hostname'] == "k8s-master01"