---
- block:

    - name: Install Nginx helm chart
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - "app.kubernetes.io/name: ingress-nginx"
        wait: yes
        wait_condition:
          reason: ready
        namespace: nginx-ingress
        wait_sleep: 10
        wait_timeout: 360

  when: "'k8s-master01' in ansible_hostname"