---
- name: Add the OS variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install Nginx ingress-controller
  include_tasks: install-nginx-ingress.yml